### ISSUE TITLE
spi brushless spindle driver

### ISSUE THREAD

**Issue by valpoder** [Smoothieware/Smoothieware#874] opened 2016-03-15 12:07 UTC
hello guys:

Would it be possible to interface a brushless motor driver chip such as allegro [A4960](http://www.allegromicro.com/~/media/Files/Datasheets/A4960-A-Automotive-Datasheet.ashx?la=en) to the smoothieboard by the SPI interface ???  

Cheers ...

**Comment by triffid** [comment] 2016-03-15 13:58
Probably, but you'd have to write a driver for it

**Comment by dandumit** [comment] 2016-03-15 14:05
Unfortunately SPI it's not for long wires. You would have to place that
driver very close to your smoothie board.

DAniel

**Comment by triffid** [comment] 2016-03-15 14:06
That's fine, the motor wires can be long especially if you braid them

**Comment by valpoder** [comment] 2016-03-15 14:10
> Probably, but you'd have to write a driver for it

what do you mean by driver???  like SPI driver ???
i thought smmothie already has SPI libraries...
i have arduino code to drive the chip by spi by the way.. i guess this can be ported somehow

**Comment by triffid** [comment] 2016-03-15 14:17
Yeah we already have SPI driver but you need to add code to tell your chip
what to do.

Due to smoothie's modular nature it'll possibly be even simpler than your
arduino code, but certainly somewhat different

**Comment by valpoder** [comment] 2016-03-15 14:19
thanks so much...

What pins/connector should i use for my spi ???
where in the code should i write my "sauce' ?

Cheers :)

**Comment by triffid** [comment] 2016-03-15 16:35
There's a spare SPI port on smoothie board, and plenty of examples for
adding new modules in smoothie's existing codebase, probably some stuff on
the wiki too.

Basically your module should check config to see if it's enabled, then
listen for relevant gcode messages and issue commands to your chip as
appropriate

**Comment by wolfmanjm** [comment] 2016-03-15 18:52
There is already a motorcontrol module that sets up SPI based stepper controllers. Look at that one to see how to do it.
https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/utils/motordrivercontrol/MotorDriverControl.cpp

**Comment by wolfmanjm** [comment] 2016-03-15 18:52
As this is a development question and not a bug report I am closing it.

**Closed by wolfmanjm** 2016-03-15 18:52 UTC
