### ISSUE TITLE
Spindle does not work on P1.23 with Network enabled

### ISSUE THREAD

**Issue by dutchrazor** [Smoothieware/Smoothieware#945] opened 2016-06-17 19:39 UTC
I had the following config which did not work:

-Spindle module enabled, with PWM pin on P1.23
-Pronterface connected via Telnet

It seems that enabling telnet interferes with the PWM out capability in 1.23. It does work fine on pins in the 2.x range.

**Comment by wolfmanjm** [comment] 2016-06-17 19:49
This did not conform to the issue submission guidelines.  https://github.com/Smoothieware/Smoothieware/blob/edge/HowToFileIssues.md

**Comment by dutchrazor** [comment] 2016-06-17 19:51
You don't want to fix it , fine by me.

**Comment by arthurwolf** [comment] 2016-06-17 19:52
That's not what that meant.
We recently added a set of rules people should follow when they create new
issues, and he pointed you at those, that's it.

If there is a problem in Smoothie, we want to fix it, make no mistake.

Thanks.

On Fri, Jun 17, 2016 at 9:51 PM, dutchrazor <notifications@github.com>
wrote:

> You don't want to fix it , fine by me.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/945#issuecomment-226865684>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGpFT5IRzDVNfqgV84If1TfsnS-DgUjks5qMvq5gaJpZM4I4q1X>
> .
>



-- 
Courage et bonne humeur.

**Comment by arthurwolf** [comment] 2016-06-17 20:00
@dutchrazor Just to be clear : closing the issue is just a way for us to sort issues. 
If you follow the issue posting rules, it will be re-opened no problem.

**Comment by dutchrazor** [comment] 2016-06-17 21:52
I hope you understand the tone may be confusing, especially since the guidelines are new.

Let's try again :) 

What were you doing?

Enable the spindle via M3 S200 (set Spindle to 200RPM) while connected to Smoothieboard via telnet.
-Spindle PWM is connected to 1.23

What did you expect to happen?

Spindle should go to 200 RPM.
-> Expected PWM output to go to 1.0, spindle to accelerate

What happened instead?

-PWM output from M957 indeed goes to 1.0
-PWM output pin 1.23 stays low

Branch & Commit or Version of Smoothieware
Tried both Edge and Master from http://triffid-hunter.no-ip.info/Smoothie.html. 

Hardware model you are using (Make, and version)
Smoothie board 5X V1a

Host and Operating System running the Host
Windows 7, Pronterface

Link to and console logs
Will upload Monday. I take it this means a log from Pronterface communication?

**Comment by wolfmanjm** [comment] 2016-06-17 22:09
Thank you, Any logs on pronterface if relevant, (Showing what you are sending and results), but also config file and result of M503 is also required.

**Comment by wolfmanjm** [comment] 2016-07-07 04:28
Closing as the requested additional information was not given.

**Closed by wolfmanjm** 2016-07-07 04:28 UTC
Labels: Awaiting more information
